import type { SiteLang } from "@/lib/services";

export const assistantContent = {
  pl: {
    sectionEyebrow: "Asystent AI",
    sectionTitle: "Zapytaj AI, co można zautomatyzować w Twojej firmie",
    sectionSubtitle:
      "Opisz, jak dziś wygląda praca w Twojej firmie, a asystent podpowie, które procesy warto zautomatyzować, jakie rozwiązanie ma sens i ile orientacyjnie kosztuje. Rozmowę wyślesz do mnie jednym kliknięciem.",
    howItWorksTitle: "Jak to działa",
    howItWorks: [
      { title: "Opisz proces", text: "Branża, co robicie ręcznie, jakich narzędzi używacie, ile zapytań albo zamówień obsługujecie." },
      { title: "Dostań propozycje", text: "Asystent zaproponuje 2-3 kierunki automatyzacji z typowym efektem i orientacyjnym budżetem." },
      { title: "Wyślij rozmowę", text: "Zostaw e-mail, a ja dostanę transkrypt i podsumowanie. Wracam w 2-5 dni z bezpłatnym prototypem lub konkretną propozycją." },
    ],
    chatTitle: "Asystent ML DevWorks",
    chatStatusOnline: "Odpowiada w kilka sekund",
    chatStatusTyping: "Pisze odpowiedź...",
    welcome:
      "Cześć! Pomogę Ci sprawdzić, co w Twojej firmie da się zautomatyzować albo zamienić w aplikację. Napisz, czym się zajmujecie i co dziś zabiera Wam najwięcej czasu - albo wybierz jeden z tematów poniżej.",
    chips: [
      "Prowadzę firmę usługową i tracę czas na telefony i maile od klientów",
      "Chcę zautomatyzować obsługę zgłoszeń i pytań klientów",
      "Ręcznie przepisuję dane między arkuszami, CRM i systemem",
      "Ile orientacyjnie kosztuje agent AI dla mojej firmy?",
      "Potrzebuję aplikacji mobilnej dla pracowników w terenie",
    ],
    chipsLabel: "Popularne tematy",
    chipsHide: "Zwiń",
    inputPlaceholder: "Napisz wiadomość…",
    inputHint: "Enter wysyła · Shift+Enter nowa linia",
    send: "Wyślij",
    stop: "Zatrzymaj",
    reset: "Nowa rozmowa",
    resetConfirm: "Zacząć nową rozmowę? Obecna zostanie usunięta.",
    close: "Zamknij asystenta",
    openFab: "Zapytaj AI",
    openFabAria: "Otwórz asystenta AI",
    sendToOwner: "Wyślij rozmowę do ML DevWorks",
    sendToOwnerHint: "Michał dostanie transkrypt i podsumowanie, a Ty odpowiedź w 2-5 dni.",
    disclaimer: "AI może się mylić. Kwoty są orientacyjne, wycena zawsze po rozmowie.",
    limitReached: "To już limit wiadomości w tej rozmowie. Wyślij ją do ML DevWorks, a Michał odpowie osobiście.",
    sentBanner: (email: string) => `Rozmowa wysłana. Michał odezwie się na ${email} w ciągu 2-5 dni.`,
    unavailableTitle: "Asystent chwilowo niedostępny",
    unavailableText: "Opisz swój pomysł albo problem w formularzu kontaktowym poniżej - odpowiem osobiście.",
    errors: {
      rate_limited: "Za dużo wiadomości w krótkim czasie. Odczekaj chwilę i spróbuj ponownie.",
      unavailable: "Asystent jest chwilowo niedostępny. Skorzystaj z formularza kontaktowego.",
      upstream: "Nie udało się pobrać odpowiedzi. Spróbuj ponownie za chwilę.",
      network: "Brak połączenia. Sprawdź internet i spróbuj ponownie.",
      invalid: "Wiadomość jest za długa albo niepoprawna.",
    },
    retry: "Spróbuj ponownie",
    form: {
      title: "Wyślij rozmowę do ML DevWorks",
      subtitle: "Zostaw e-mail, żebym mógł odpowiedzieć. Pozostałe pola są opcjonalne, ale przyspieszą przygotowanie prototypu.",
      email: "Twój e-mail",
      name: "Imię (opcjonalnie)",
      phone: "Telefon (opcjonalnie)",
      company: "Firma (opcjonalnie)",
      consent:
        "Wyrażam zgodę na kontakt w sprawie mojego zapytania i przetwarzanie danych z tej rozmowy przez ML DevWorks w tym celu.",
      submit: "Wyślij do ML DevWorks",
      submitting: "Wysyłanie...",
      cancel: "Wróć do rozmowy",
      emailInvalid: "Podaj poprawny adres e-mail.",
      consentRequired: "Zgoda jest wymagana, żeby móc odpowiedzieć.",
      successTitle: "Wysłane!",
      successText: (email: string) =>
        `Dziękuję. Rozmowa trafiła do Michała. Odpowiedź przyjdzie na ${email} zwykle w ciągu 2-5 dni - często razem z bezpłatnym prototypem.`,
      errorGeneric: "Nie udało się wysłać. Spróbuj ponownie albo napisz na office@ml-devworks.com.",
      errorRate: "Za dużo wysyłek w krótkim czasie. Spróbuj za kilka minut.",
      privacyNote: "Dane wykorzystuję wyłącznie do odpowiedzi na to zapytanie. Nie zapisuję rozmowy w bazie - trafia tylko na moją skrzynkę.",
    },
    a11y: {
      log: "Rozmowa z asystentem AI",
      assistantTyping: "Asystent pisze odpowiedź",
      assistantDone: "Odpowiedź gotowa",
      userLabel: "Ty",
      assistantLabel: "Asystent",
    },
  },
  en: {
    sectionEyebrow: "AI advisor",
    sectionTitle: "Ask AI what can be automated in your company",
    sectionSubtitle:
      "Describe how work looks in your company today and the assistant will suggest which processes are worth automating, what kind of solution makes sense, and a rough budget. One click sends the conversation to me.",
    howItWorksTitle: "How it works",
    howItWorks: [
      { title: "Describe the process", text: "Industry, what you do manually, which tools you use, how many enquiries or orders you handle." },
      { title: "Get suggestions", text: "The assistant proposes 2-3 automation directions with typical effects and an indicative budget." },
      { title: "Send the conversation", text: "Leave your email and I receive the transcript and summary. I reply within 2-5 days with a free prototype or a concrete proposal." },
    ],
    chatTitle: "ML DevWorks assistant",
    chatStatusOnline: "Replies in seconds",
    chatStatusTyping: "Typing...",
    welcome:
      "Hi! I can help you find out what in your company can be automated or turned into an app. Tell me what you do and what takes the most time today - or pick one of the topics below.",
    chips: [
      "I run a service business and lose time on customer calls and emails",
      "I want to automate ticket handling and customer questions",
      "I copy data manually between spreadsheets, CRM and our system",
      "Roughly how much does an AI agent for my company cost?",
      "I need a mobile app for field employees",
    ],
    chipsLabel: "Popular topics",
    chipsHide: "Hide",
    inputPlaceholder: "Type a message…",
    inputHint: "Enter sends · Shift+Enter new line",
    send: "Send",
    stop: "Stop",
    reset: "New conversation",
    resetConfirm: "Start a new conversation? The current one will be removed.",
    close: "Close assistant",
    openFab: "Ask AI",
    openFabAria: "Open the AI assistant",
    sendToOwner: "Send conversation to ML DevWorks",
    sendToOwnerHint: "Michał receives the transcript and summary; you get a reply within 2-5 days.",
    disclaimer: "AI can make mistakes. Amounts are indicative; the estimate follows a conversation.",
    limitReached: "You reached the message limit for this conversation. Send it to ML DevWorks and Michał will reply personally.",
    sentBanner: (email: string) => `Conversation sent. Michał will reply to ${email} within 2-5 days.`,
    unavailableTitle: "Assistant temporarily unavailable",
    unavailableText: "Describe your idea or problem in the contact form below - I will reply personally.",
    errors: {
      rate_limited: "Too many messages in a short time. Wait a moment and try again.",
      unavailable: "The assistant is temporarily unavailable. Please use the contact form.",
      upstream: "Could not get a reply. Please try again in a moment.",
      network: "No connection. Check your internet and try again.",
      invalid: "The message is too long or invalid.",
    },
    retry: "Try again",
    form: {
      title: "Send conversation to ML DevWorks",
      subtitle: "Leave your email so I can reply. Other fields are optional but speed up prototype preparation.",
      email: "Your email",
      name: "Name (optional)",
      phone: "Phone (optional)",
      company: "Company (optional)",
      consent:
        "I agree to be contacted about my enquiry and to the processing of the data from this conversation by ML DevWorks for that purpose.",
      submit: "Send to ML DevWorks",
      submitting: "Sending...",
      cancel: "Back to conversation",
      emailInvalid: "Enter a valid email address.",
      consentRequired: "Consent is required so I can reply.",
      successTitle: "Sent!",
      successText: (email: string) =>
        `Thank you. The conversation reached Michał. A reply will arrive at ${email} usually within 2-5 days - often together with a free prototype.`,
      errorGeneric: "Sending failed. Try again or write to office@ml-devworks.com.",
      errorRate: "Too many submissions in a short time. Try again in a few minutes.",
      privacyNote: "I use the data only to reply to this enquiry. The conversation is not stored in a database - it goes only to my inbox.",
    },
    a11y: {
      log: "Conversation with the AI assistant",
      assistantTyping: "The assistant is typing",
      assistantDone: "Reply ready",
      userLabel: "You",
      assistantLabel: "Assistant",
    },
  },
} satisfies Record<SiteLang, unknown>;

export type AssistantContent = (typeof assistantContent)["pl"];
